services:
  static-server:
    image: nginx:latest
    container_name: static_server
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/static.conf:/etc/nginx/conf.d/default.conf
      - ./images:/usr/share/nginx/html

  cache-proxy:
    image: openresty/openresty:latest
    platform: linux/amd64
    container_name: cache_proxy
    volumes:
      - ./nginx/cache.conf:/etc/nginx/conf.d/default.conf
      - ./cache:/var/cache/nginx
    ports:
      - "80:80"

volumes:
  cache:
